[project]
name = "my-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.0",
    "fastapi>=0.115.12",
    "geopandas>=1.0.1",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "uvicorn>=0.34.2",
]
